-- =============================================================================
-- modoverrides.lua — auto-generated by manage-mods.sh
-- Source of truth: data/mods/mods.conf
-- =============================================================================

return {
  -- (no mods configured)
}
