#!/usr/bin/env pwsh
param(
    [Parameter(Position = 0)]
    [ValidateSet('add', 'remove', 'enable', 'disable', 'list', 'sync')]
    [string]$Command,

    [Parameter(Position = 1)]
    [string]$ModId,

    [Parameter(Position = 2)]
    [string]$Config
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $PSScriptRoot
$ModsConf = Join-Path $ScriptDir 'data\mods\mods.conf'
$SetupLua = Join-Path $ScriptDir 'data\mods\dedicated_server_mods_setup.lua'
$OverridesLua = Join-Path $ScriptDir 'data\save\Cluster_1\modoverrides.lua'

function Show-Usage {
    @"
Usage: manage-mods.ps1 <command> [args]

Commands:
  add <id> [config]    Add a mod (config: "KEY=val,KEY2=val2")
  remove <id>          Remove a mod
  enable <id>          Enable a mod
  disable <id>         Disable a mod
  list                 List all mods with status
  sync                 Regenerate Lua files and download mods

Examples:
  manage-mods.ps1 add 378160973 "SHOWFIREICONS=true,SHAREMINIMAPPROGRESS=true"
  manage-mods.ps1 add 351325790
  manage-mods.ps1 remove 351325790
  manage-mods.ps1 list
  manage-mods.ps1 sync
"@
}

function Ensure-Conf {
    if (-not (Test-Path $ModsConf)) {
        New-Item -ItemType File -Path $ModsConf -Force | Out-Null
    }
}

function Read-Mods {
    Ensure-Conf
    Get-Content $ModsConf | Where-Object {
        $_ -match '^\d+' -and $_ -notmatch '^\s*#'
    } | ForEach-Object {
        $parts = $_ -split '\s+', 3
        [PSCustomObject]@{
            Id      = $parts[0]
            Enabled = if ($parts[1] -eq 'true') { $true } else { $false }
            Config  = if ($parts.Count -ge 3) { $parts[2] } else { '' }
        }
    }
}

function Write-Mods {
    param($Mods)
    Ensure-Conf
    $content = Get-Content $ModsConf | Where-Object { $_ -match '^\s*#' }
    foreach ($m in $Mods) {
        $content += "$($m.Id)  $($m.Enabled.ToString().ToLower())  $($m.Config)"
    }
    Set-Content $ModsConf $content
}

function Format-LuaValue {
    param($val)
    if ($val -match '^\d+(\.\d+)?$' -or $val -match '^true$' -or $val -match '^false$') {
        return "$val"
    }
    return "`"$val`""
}

# ── Commands ──────────────────────────────────────────

function Add-Mod {
    param($id, $config)
    Ensure-Conf
    $existing = Read-Mods | Where-Object { $_.Id -eq $id }
    if ($existing) {
        Write-Host "Mod $id already exists. Use enable/disable to toggle."
        exit 1
    }
    Add-Content $ModsConf "$id  true  $config"
    Write-Host "✓ Added mod $id (enabled)"
}

function Remove-Mod {
    param($id)
    $mods = Read-Mods | Where-Object { $_.Id -ne $id }
    $removed = (Read-Mods | Where-Object { $_.Id -eq $id }).Count -gt 0
    if (-not $removed) {
        Write-Host "Mod $id not found."
        exit 1
    }
    Write-Mods $mods
    Write-Host "✓ Removed mod $id"
}

function Enable-Mod {
    param($id)
    $mods = Read-Mods | ForEach-Object {
        if ($_.Id -eq $id) { $_.Enabled = $true }
        $_
    }
    Write-Mods $mods
    Write-Host "✓ Enabled mod $id"
}

function Disable-Mod {
    param($id)
    $mods = Read-Mods | ForEach-Object {
        if ($_.Id -eq $id) { $_.Enabled = $false }
        $_
    }
    Write-Mods $mods
    Write-Host "✓ Disabled mod $id"
}

function List-Mods {
    $mods = Read-Mods
    if (-not $mods) {
        Write-Host "No mods configured."
        Write-Host "Add one: manage-mods.ps1 add <workshop_id>"
        return
    }
    Write-Host ("{0,-15} {1,-8} {2}" -f 'ID', 'ENABLED', 'CONFIG')
    Write-Host ("{0,-15} {1,-8} {2}" -f '---', '-------', '------')
    foreach ($m in $mods) {
        Write-Host ("{0,-15} {1,-8} {2}" -f $m.Id, $m.Enabled.ToString().ToLower(), $m.Config)
    }
}

function Sync-Mods {
    $mods = Read-Mods
    $hasMods = $mods.Count -gt 0

    # Generate dedicated_server_mods_setup.lua
    Write-Host "Generating $SetupLua ..."
    @"
-- =============================================================================
-- dedicated_server_mods_setup.lua -- auto-generated by manage-mods.ps1
-- Source of truth: data/mods/mods.conf
-- =============================================================================

"@ | Set-Content $SetupLua

    if ($hasMods) {
        foreach ($m in $mods) {
            Add-Content $SetupLua "ServerModSetup(`"$($m.Id)`")"
        }
    } else {
        Add-Content $SetupLua "-- (no mods configured)"
    }

    # Generate modoverrides.lua
    Write-Host "Generating $OverridesLua ..."
    @"
-- =============================================================================
-- modoverrides.lua -- auto-generated by manage-mods.ps1
-- Source of truth: data/mods/mods.conf
-- =============================================================================

return {
"@ | Set-Content $OverridesLua

    if ($hasMods) {
        foreach ($m in $mods) {
            if (-not $m.Enabled) {
                Add-Content $OverridesLua "  -- [``workshop-$($m.Id)``] = { enabled = false },"
                continue
            }
            if ($m.Config) {
                Add-Content $OverridesLua "  [``workshop-$($m.Id)``] = {"
                Add-Content $OverridesLua "    enabled = true,"
                Add-Content $OverridesLua "    configuration_options = {"
                foreach ($pair in ($m.Config -split ',')) {
                    $kv = $pair -split '=', 2
                    $val = Format-LuaValue $kv[1]
                    Add-Content $OverridesLua "      $($kv[0]) = $val,"
                }
                Add-Content $OverridesLua "    },"
                Add-Content $OverridesLua "  },"
            } else {
                Add-Content $OverridesLua "  [``workshop-$($m.Id)``] = { enabled = true },"
            }
        }
    } else {
        Add-Content $OverridesLua "  -- (no mods configured)"
    }

    Add-Content $OverridesLua "}"

    Write-Host "✓ Regenerated Lua files"
    Write-Host "Running mod updater ..."

    Set-Location $ScriptDir
    docker compose --profile mod-update run --rm dst-mod-updater

    Write-Host ""
    Write-Host "✓ All done! Restart the server to apply:"
    Write-Host "  docker compose restart"
}

# ── Main ──────────────────────────────────────────────

if (-not $Command) {
    Show-Usage
    exit 1
}

switch ($Command) {
    'add' {
        if (-not $ModId) { Show-Usage; exit 1 }
        Add-Mod $ModId $Config
    }
    'remove' {
        if (-not $ModId) { Show-Usage; exit 1 }
        Remove-Mod $ModId
    }
    'enable' {
        if (-not $ModId) { Show-Usage; exit 1 }
        Enable-Mod $ModId
    }
    'disable' {
        if (-not $ModId) { Show-Usage; exit 1 }
        Disable-Mod $ModId
    }
    'list' { List-Mods }
    'sync' { Sync-Mods }
}
