#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODS_CONF="$SCRIPT_DIR/data/mods/mods.conf"
SETUP_LUA="$SCRIPT_DIR/data/mods/dedicated_server_mods_setup.lua"
OVERRIDES_LUA="$SCRIPT_DIR/data/save/Cluster_1/modoverrides.lua"

usage() {
    cat <<EOF
Usage: manage-mods.sh <command> [args]

Commands:
  add <id> [config]    Add a mod (config: "KEY=val,KEY2=val2")
  remove <id>          Remove a mod
  enable <id>          Enable a mod
  disable <id>         Disable a mod
  list                 List all mods with status
  sync                 Regenerate Lua files and download mods

Examples:
  manage-mods.sh add 378160973 "SHOWFIREICONS=true,SHAREMINIMAPPROGRESS=true"
  manage-mods.sh add 351325790
  manage-mods.sh remove 351325790
  manage-mods.sh list
  manage-mods.sh sync
EOF
}

ensure_conf() {
    [ -f "$MODS_CONF" ] || touch "$MODS_CONF"
}

cmd_add() {
    local id="$1"
    local config="${2:-}"
    ensure_conf
    if grep -q "^$id[[:space:]]" "$MODS_CONF" 2>/dev/null; then
        echo "Mod $id already exists. Use enable/disable to toggle."
        exit 1
    fi
    echo "$id  true  $config" >> "$MODS_CONF"
    echo "✓ Added mod $id (enabled)"
}

cmd_remove() {
    local id="$1"
    ensure_conf
    if ! grep -q "^$id[[:space:]]" "$MODS_CONF" 2>/dev/null; then
        echo "Mod $id not found."
        exit 1
    fi
    grep -v "^$id[[:space:]]" "$MODS_CONF" > "$MODS_CONF.tmp" && mv "$MODS_CONF.tmp" "$MODS_CONF"
    echo "✓ Removed mod $id"
}

cmd_enable() {
    local id="$1"
    ensure_conf
    sed -i "s/^$id[[:space:]]*false/$id  true/" "$MODS_CONF"
    echo "✓ Enabled mod $id"
}

cmd_disable() {
    local id="$1"
    ensure_conf
    sed -i "s/^$id[[:space:]]*true/$id  false/" "$MODS_CONF"
    echo "✓ Disabled mod $id"
}

cmd_list() {
    ensure_conf
    if [ ! -s "$MODS_CONF" ]; then
        echo "No mods configured."
        echo "Add one: manage-mods.sh add <workshop_id>"
        exit 0
    fi
    printf "%-15s %-8s  %s\n" "ID" "ENABLED" "CONFIG"
    printf "%-15s %-8s  %s\n" "---" "-------" "------"
    while IFS='' read -r line || [ -n "$line" ]; do
        line="$(echo "$line" | sed 's/#.*//' | xargs)"
        [ -z "$line" ] && continue
        read -r id enabled config <<< "$line"
        printf "%-15s %-8s  %s\n" "$id" "$enabled" "${config:-}"
    done < "$MODS_CONF"
}

cmd_sync() {
    ensure_conf
    echo "Generating $SETUP_LUA ..."
    cat > "$SETUP_LUA" << 'LUA_HEADER'
-- =============================================================================
-- dedicated_server_mods_setup.lua — auto-generated by manage-mods.sh
-- Source of truth: data/mods/mods.conf
-- =============================================================================
LUA_HEADER

    echo "" >> "$SETUP_LUA"

    found=false
    while IFS='' read -r line || [ -n "$line" ]; do
        line="$(echo "$line" | sed 's/#.*//' | xargs)"
        [ -z "$line" ] && continue
        read -r id enabled config <<< "$line"
        echo "ServerModSetup(\"$id\")" >> "$SETUP_LUA"
        found=true
    done < "$MODS_CONF"

    if [ "$found" = false ]; then
        echo "-- (no mods configured)" >> "$SETUP_LUA"
    fi

    echo "Generating $OVERRIDES_LUA ..."
    cat > "$OVERRIDES_LUA" << 'LUA_HEADER'
-- =============================================================================
-- modoverrides.lua — auto-generated by manage-mods.sh
-- Source of truth: data/mods/mods.conf
-- =============================================================================

return {
LUA_HEADER

    found=false
    while IFS='' read -r line || [ -n "$line" ]; do
        line="$(echo "$line" | sed 's/#.*//' | xargs)"
        [ -z "$line" ] && continue
        read -r id enabled config <<< "$line"

        if [ "$enabled" != "true" ]; then
            echo "  -- [\"workshop-$id\"] = { enabled = false }," >> "$OVERRIDES_LUA"
            found=true
            continue
        fi

        if [ -n "$config" ]; then
            echo "  [\"workshop-$id\"] = {" >> "$OVERRIDES_LUA"
            echo "    enabled = true," >> "$OVERRIDES_LUA"
            echo "    configuration_options = {" >> "$OVERRIDES_LUA"
            IFS=',' read -ra pairs <<< "$config"
            for pair in "${pairs[@]}"; do
                key="${pair%%=*}"
                val="${pair#*=}"
                # If value is numeric or boolean, emit unquoted
                if [[ "$val" =~ ^[0-9]+(\.[0-9]+)?$ || "$val" =~ ^true$ || "$val" =~ ^false$ ]]; then
                    echo "      $key = $val," >> "$OVERRIDES_LUA"
                else
                    echo "      $key = \"$val\"," >> "$OVERRIDES_LUA"
                fi
            done
            echo "    }," >> "$OVERRIDES_LUA"
            echo "  }," >> "$OVERRIDES_LUA"
        else
            echo "  [\"workshop-$id\"] = { enabled = true }," >> "$OVERRIDES_LUA"
        fi
        found=true
    done < "$MODS_CONF"

    if [ "$found" = false ]; then
        echo "  -- (no mods configured)" >> "$OVERRIDES_LUA"
    fi

    echo "}" >> "$OVERRIDES_LUA"

    echo "✓ Regenerated Lua files"
    echo "Running mod updater (download/update mods) ..."
    cd "$SCRIPT_DIR"
    docker compose --profile mod-update run --rm dst-mod-updater

    echo ""
    echo "✓ All done! Restart the server to apply:"
    echo "  docker compose restart"
}

[ $# -lt 1 ] && { usage; exit 1; }
cmd="$1"
shift

case "$cmd" in
    add)    [ $# -ge 1 ] || { usage; exit 1; }; cmd_add "$@" ;;
    remove) [ $# -ge 1 ] || { usage; exit 1; }; cmd_remove "$@" ;;
    enable) [ $# -ge 1 ] || { usage; exit 1; }; cmd_enable "$@" ;;
    disable) [ $# -ge 1 ] || { usage; exit 1; }; cmd_disable "$@" ;;
    list)   cmd_list ;;
    sync)   cmd_sync ;;
    *)      usage; exit 1 ;;
esac
