-- =============================================================================
-- modoverrides.lua -- auto-generated by manage-mods.ps1
-- Source of truth: data/mods/mods.conf
-- =============================================================================

return {
  ["workshop-378160973"] = {
    enabled = true,
    configuration_options = {
      SHOWFIREICONS = true,
      SHAREMINIMAPPROGRESS = true,
    },
  },
  ["workshop-375859599"] = { enabled = true },
  ["workshop-376333686"] = { enabled = true },
  ["workshop-351325790"] = { enabled = true },
}
